### ISSUE TITLE
Restore the resource manager to keeping one copy of each resource

### ISSUE THREAD

**Issue by Sage-of-Mirrors** [LordNed/Winditor#13]
When the resource system was refactored, it was made inefficient to prevent all models sharing a resource from animating when only one instance of an actor using that resource is selected. The system must be modified to keep only one copy of each resource; this means that the aforementioned bug will persist (all models of a single type animating when only one instance is selected), but it will be much more efficient.

**Comment by LagoLunatic** [comment]
>all models of a single type animating when only one instance is selected

Based on my testing, I think this would also apply to BRK animations - which would be confusing, since entities that change their colors like chuchus would all look the same even if they're different colors.

IMO this issue is less serious with the ability to open single rooms, if the user runs out of memory opening an entire stage they can just open whichever room they want to edit and I think it will work.
