### ISSUE TITLE
Scene BGM Editor does not change music

### ISSUE THREAD

**Issue by fuhreak** [LordNed/Winditor#47]
Changing the dropdown menus in the Scene BGM Editor menu appears to do nothing.
The changes appear to save as the new settings appear every time the editor is relaunched.
Entries can be added but not removed, as the remove button does nothing.

For sanity testing I took a simple map and removed all references to room settings, stage settings, events and various other settings.
I was still unable to track down where it would be playing music outside of the settings within Scene BGM nor change the music in Scene BGM.
Creating a new map and applying the settings of another map also did not work.

Steps to reproduce: Take any map and change the Type, Name and/or Wave Bank 1~4 values

**Comment by LagoLunatic** [comment]
Did you apply the `bgm_file.asm` patch to your project using https://github.com/LagoLunatic/WW_Hacking_API?

That patch is required to edit music and Winditor itself currently cannot apply it automatically. Winditor only creates a new file with your custom music selection in it, while that patch modifies the game engine to use the file instead of the vanilla data.

**Comment by fuhreak** [comment]
This did fix it, I would like to suggest either adding a link to the currently unused "Tutorial" button in the Scene BGM Editor until Winditor can apply this by itself.
